debian latest:
  image: debian:latest
  stage: build
  before_script:
    - apt-get update --quiet
    - apt-get --assume-yes --quiet install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

ubuntu 19.10:
  image: ubuntu:19.10
  stage: build
  before_script:
    - apt-get update
    - apt-get --assume-yes --quiet install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

fedora latest:
  image: fedora:latest
  stage: build
  before_script:
    # Project
    - dnf install --assumeyes --quiet openssl-devel
    # Build System
    - dnf install --assumeyes --quiet cmake make clang
    - export CC=/usr/bin/clang
    # Packaging
    - dnf install --assumeyes --quiet rpm-build rpmlint
  script: "./scripts/build_fedora_rpm.sh"

mageia 7:
  # "latest" points to 6
  image: mageia:7
  stage: build
  before_script:
    - dnf install --assumeyes --quiet cmake make clang openssl-devel
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

archlinux latest:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman --quiet --sync --refresh --sysupgrade --needed --noprogressbar --noconfirm cmake make clang openssl
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

clearlinux latest:
  image: clearlinux:latest
  stage: build
  before_script:
    - swupd bundle-add --no-progress --quiet c-basic devpkg-openssl
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"
