# GitLab hosts a Container Registry, but these containers count towards the repository size limit.
# With the number of distributions supported, we would be close to that limit.

stages:
  - build
  - deploy

debian latest build:
  image: lptech1024/imagecrypt:build-debian_latest
  stage: build
  script: "./scripts/build_generic.sh"
  artifacts:
    when: on_success
    paths:
      - build/*.sh

debian latest deploy:
  image: lptech1024/imagecrypt:deploy-debian_latest
  stage: deploy
  needs:
    - job: debian latest build
      artifacts: true
  script: "./build/*.sh --skip-license"

ubuntu 19.10 build:
  image: lptech1024/imagecrypt:build-ubuntu_19_10
  stage: build
  script: "./scripts/build_generic.sh"
  artifacts:
    when: on_success
    paths:
      - build/*.sh

ubuntu 19.10 deploy:
  image: lptech1024/imagecrypt:deploy-ubuntu_19_10
  stage: deploy
  needs:
    - job: ubuntu 19.10 build
      artifacts: true
  script: "./build/*.sh --skip-license"

ubuntu 20.04 build:
  image: lptech1024/imagecrypt:build-ubuntu_20_04
  stage: build
  script: "./scripts/build_generic.sh"
  artifacts:
    when: on_success
    paths:
      - build/*.sh

ubuntu 20.04 deploy:
  image: lptech1024/imagecrypt:deploy-ubuntu_20_04
  stage: deploy
  needs:
    - job: ubuntu 20.04 build
      artifacts: true
  script: "./build/*.sh --skip-license"

centos latest build:
  image: lptech1024/imagecrypt:build-centos_latest
  stage: build
  script: "./scripts/build_generic.sh"
  artifacts:
    when: on_success
    paths:
      - build/*.sh

centos latest deploy:
  image: lptech1024/imagecrypt:deploy-centos_latest
  stage: deploy
  needs:
    - job: centos latest build
      artifacts: true
  script: "./build/*.sh --skip-license"

fedora latest build:
  image: lptech1024/imagecrypt:build-fedora_latest
  stage: build
  script: "./scripts/build_fedora_rpm.sh"
  artifacts:
    when: on_success
    paths:
      - custom_rpm_build/*.rpm

fedora latest deploy:
  image: lptech1024/imagecrypt:deploy-fedora_latest
  stage: deploy
  needs:
    - job: fedora latest build
      artifacts: true
  script: "dnf install --assumeyes --verbose custom_rpm_build/*.rpm"

mageia 7 build:
  image: lptech1024/imagecrypt:build-mageia_7
  stage: build
  script: "./scripts/build_generic.sh"
  artifacts:
      when: on_success
      paths:
        - build/*.sh

mageia 7 deploy:
  image: lptech1024/imagecrypt:deploy-mageia_7
  stage: deploy
  needs:
    - job: mageia 7 build
      artifacts: true
  script: "./build/*.sh --skip-license"

archlinux latest build:
  image: lptech1024/imagecrypt:build-archlinux_latest
  stage: build
  script: "./scripts/build_generic.sh"
  artifacts:
    when: on_success
    paths:
      - build/*.sh

archlinux latest deploy:
  image: lptech1024/imagecrypt:deploy-archlinux_latest
  stage: deploy
  needs:
    - job: archlinux latest build
      artifacts: true
  script: "./build/*.sh --skip-license"

clearlinux latest build:
  image: lptech1024/imagecrypt:build-clearlinux_latest
  stage: build
  script: "./scripts/build_generic.sh"
  artifacts:
    when: on_success
    paths:
      - build/*.sh

clearlinux latest deploy:
  image: lptech1024/imagecrypt:deploy-clearlinux_latest
  stage: deploy
  needs:
    - job: clearlinux latest build
      artifacts: true
  script: "./build/*.sh --skip-license"
