# ubuntu:19.10 should also work
image: ubuntu:20.04

before_script:
  - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
  - export CC=/usr/bin/clang

imagecrypt:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
