image: ubuntu:18.04

before_script:
  - apt-get update && apt-get -y install cmake make clang libssl-dev

imagecrypt:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
