ubuntu 19.10:
  image: ubuntu:19.10
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

ubuntu 20.04:
  image: ubuntu:20.04
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

fedora latest:
  image: fedora:latest
  stage: build
  before_script:
    - dnf install -y cmake make clang clang openssl-devel
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
