stages:
  - build
  - deploy

debian latest:
  image: debian:latest
  stage: build
  before_script:
    - apt-get update --quiet
    - apt-get --assume-yes --quiet install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

ubuntu 19.10:
  image: ubuntu:19.10
  stage: build
  before_script:
    - apt-get update --quiet
    - apt-get --assume-yes --quiet install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

ubuntu 20.04:
  image: ubuntu:20.04
  stage: build
  before_script:
    - apt-get update --quiet
    - apt-get --assume-yes --quiet install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

centos latest:
  image: centos:latest
  stage: build
  before_script:
    - dnf install --assumeyes --quiet make clang openssl-devel
    # Using to install compliant cmake version
    - dnf install --assumeyes --quiet python3-pip
    - pip3 install --quiet cmake==3.13.3
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

fedora latest build:
  image: fedora:latest
  stage: build
  before_script:
    # Project
    - dnf install --assumeyes --quiet openssl-devel
    # Build System
    - dnf install --assumeyes --quiet cmake make clang
    - export CC=/usr/bin/clang
    # Packaging
    - dnf install --assumeyes --quiet rpm-build rpmlint
  script: "./scripts/build_fedora_rpm.sh"
  artifacts:
    when: on_success
    paths:
      - custom_rpm_build/*.rpm

fedora latest deploy:
  image: fedora:latest
  stage: deploy
  needs:
    - job: fedora latest build
      artifacts: true
  before_script:
    - dnf update --assumeyes --quiet openssl dnf
  script:
    - dnf install --assumeyes custom_rpm_build/*.rpm

mageia 7:
  # "latest" points to 6
  image: mageia:7
  stage: build
  before_script:
    - dnf install --assumeyes --quiet cmake make clang openssl-devel
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

archlinux latest:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman --quiet --sync --refresh --sysupgrade --needed --noprogressbar --noconfirm cmake make clang openssl
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"

clearlinux latest:
  image: clearlinux:latest
  stage: build
  before_script:
    - swupd bundle-add --no-progress --quiet c-basic devpkg-openssl
    - export CC=/usr/bin/clang
  script: "./scripts/build_generic.sh"
