debian latest:
  image: debian:latest
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script: "./scripts/build_fedora_rpm.sh"

ubuntu 19.10:
  image: ubuntu:19.10
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script: "./scripts/build_fedora_rpm.sh"

fedora latest:
  image: fedora:latest
  stage: build
  before_script:
    # Project
    - dnf install -y openssl-devel
    # Build System
    - dnf install -y cmake make clang
    - export CC=/usr/bin/clang
    # Packaging
    - dnf install -y rpm-build rpmlint
  script: "./scripts/build_fedora_rpm.sh"

mageia 7:
  # "latest" points to 6
  image: mageia:7
  stage: build
  before_script:
    - dnf install -y cmake make clang openssl-devel
    - export CC=/usr/bin/clang
  script: "./scripts/build_fedora_rpm.sh"

archlinux latest:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman --quiet --sync --refresh --sysupgrade --needed --noprogressbar --noconfirm cmake make clang openssl
    - export CC=/usr/bin/clang
  script: "./scripts/build_fedora_rpm.sh"

clearlinux latest:
  image: clearlinux:latest
  stage: build
  before_script:
    - swupd bundle-add c-basic devpkg-openssl
    - export CC=/usr/bin/clang
  script: "./scripts/build_fedora_rpm.sh"
