debian latest:
  image: debian:latest
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

ubuntu 19.10:
  image: ubuntu:19.10
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

ubuntu 20.04:
  image: ubuntu:20.04
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake make clang clang-tidy libssl-dev
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

centos latest:
  image: centos:latest
  stage: build
  before_script:
    - dnf install -y make clang openssl-devel
    # Using to install compliant cmake version
    - dnf install -y python3-pip
    # CMake 3.16.3 will not install (even with scikit-build)
    - pip3 install cmake==3.13.3
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

fedora latest:
  image: fedora:latest
  stage: build
  before_script:
    - dnf install -y cmake make clang openssl-devel
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

archlinux latest:
  image: archlinux:latest
  stage: build
  before_script:
    - pacman --quiet --sync --refresh --sysupgrade --needed --noprogressbar --noconfirm cmake make clang openssl
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make

clearlinux latest:
  image: clearlinux:latest
  stage: build
  before_script:
    - swupd bundle-add c-basic devpkg-openssl
    - export CC=/usr/bin/clang
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make
